#!/usr/bin/env python3
"""Derive this unit's testbench schematic from the committed Monte Carlo
campaign's own, re-pointed at the degraded DUT (issue #195).

What this unit's testbench is, exactly
--------------------------------------

`sim/pll-lock-mc`'s campaign and this one have to be **the same experiment**
except for one stated degradation, or the control's samples are not comparable
with the population they are supposed to separate from. This script is what
makes that checkable rather than asserted:

`tb_pll_lock_mc_negative_control.sch` is
`sim/pll-lock-mc/testbench/tb_pll_lock_mc.sch`'s own body, **verbatim**, with
exactly one substitution -- its single `XXTOP` instance re-pointed from
`design/top/top.sym` at the degraded top-level symbol under
`sim/lf-c2-jitter-sensitivity/testbench/`. Supply, the 10 MHz reference, the
power-on reset stimulus and the `NSEL[5:0]`=`011000` (N=25) strapping are
therefore bit-identical to the campaign's, and like it this schematic carries no
`.tran` card of its own: the window comes from `tb.json` via
`sim/harness/measure.py`.

The degraded DUT is **not re-derived here.** It is the same generated netlist
`sim/lf-c1-jitter-sensitivity` measured -- the unit that established, by
simulation, which degradation factor misses ratified row 9's bound while still
locking (`C1` area/12: 1.274 % RMS against the nominal's 0.523 %, locked).
Pointing at that unit's committed symbol rather than making a second copy is
deliberate: a second copy could drift from the one the sizing evidence was taken
on, and then this unit's DUT and its own justification would be different
circuits. `sim/lf-c1-jitter-sensitivity/testbench/gen_c1_variant.py` is the
generator that derives it from `design/`, with its own `--check`.

Usage
-----

    python3 sim/pll-lock-mc-negative-control/testbench/gen_tb.py --check
    python3 sim/pll-lock-mc-negative-control/testbench/gen_tb.py --write
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]

#: The sizing unit's arm this control's DUT is. Changing it means re-running the
#: campaign: the record names the arm it drew, and the committed `tb.json`'s
#: `negative_control.degradation` has to agree with it.
ARM = "top_c1div12"
ARM_UNIT = "sim/lf-c1-jitter-sensitivity"

NOMINAL_TB = "sim/pll-lock-mc/testbench/tb_pll_lock_mc.sch"
OUT_NAME = "tb_pll_lock_mc_negative_control.sch"

_HEADER_MARKER = "}\nG {}\n"
_XXTOP = "C {design/top/top.sym} 0 0 0 0 {name=XXTOP}"


class GenError(RuntimeError):
    pass


def derive() -> str:
    text = (REPO / NOMINAL_TB).read_text()
    _head, marker, rest = text.partition(_HEADER_MARKER)
    if not marker:
        raise GenError(f"{NOMINAL_TB}: no `v {{...}}` header block found")
    # The `v { ... }` block's closing brace belongs to the body, so a header
    # written here cannot leave that block unclosed.
    body = _HEADER_MARKER + rest
    if _XXTOP not in body:
        raise GenError(
            f"{NOMINAL_TB}'s XXTOP instance line is not the one this generator "
            f"substitutes into (expected {_XXTOP!r})"
        )
    body = body.replace(
        _XXTOP, f"C {{{ARM_UNIT}/testbench/{ARM}.sym}} 0 0 0 0 {{name=XXTOP}}", 1
    )
    header = f"""v {{xschem version=3.4.7 file_version=1.2
* {OUT_NAME} -- T1 item 6's negative control for
* sim/pll-lock-mc's campaign: the SAME testbench, with a DELIBERATELY DEGRADED
* DUT.
*
* Generated by sim/pll-lock-mc-negative-control/testbench/gen_tb.py from
* {NOMINAL_TB}. The body below is that file's own,
* verbatim, with exactly one substitution: the XXTOP instance's symbol
* ({ARM_UNIT}/testbench/{ARM}.sym instead of
* design/top/top.sym). Supply, the 10 MHz reference, the power-on reset
* stimulus and the NSEL[5:0]=011000 (N=25) strapping are bit-identical to the
* campaign's, and like it this schematic carries no `.tran` card -- the window
* comes from this unit's tb.json via sim/harness/measure.py.
*
* The degraded DUT is the arm {ARM_UNIT} MEASURED, not a
* fresh copy of it: see gen_tb.py's own docstring for why this points at that
* unit's committed symbol rather than duplicating the netlist.
*
* Nothing under design/ instantiates any of it, and no spec row is claimed for
* it. Its whole purpose is to be worse than the design at exactly one thing.
"""
    return header + body


def run(*, write: bool) -> int:
    content = derive()
    dst = HERE / OUT_NAME
    if write:
        dst.write_text(content)
        print(f"wrote {dst.relative_to(REPO)}")
        return 0
    have = dst.read_text() if dst.exists() else ""
    if have != content:
        print(f"DRIFT: {dst.relative_to(REPO)}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                have.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile="committed",
                tofile="re-derived",
            )
        )
        return 1
    print(f"OK: {OUT_NAME} is {NOMINAL_TB}'s body with only the {ARM} substitution")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="(re-)write the schematic")
    mode.add_argument(
        "--check", action="store_true", help="re-derive and diff (default)"
    )
    args = parser.parse_args(argv)
    try:
        return run(write=args.write)
    except (GenError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
